### ISSUE TITLE
[Clarification needed] Is "and" in let and loop clauses allowed, forbidden, or mandatory? 

### ISSUE THREAD

**Issue by mbiely** [schani/SimpLang#2]
The examples in README.md do not have and between bindings in _let_ clauses, e.g.:

```
let a = 1
    b = a + 1
in
    b
end
```

In examples/div.sl, there is one

```
 let multiplier = sign (x) * sign (y) and
      x = x * sign (x) and ...
```

The inconsistency in the examples seems to indicate "and" is allowed.
For _loop_ examples are consistent, but still the status of "and" is not specified.

**Comment by schani** [comment]
It's mandatory - the README was erroneous.
